const QUIZ_DURATION_SECONDS = 120;
const MIN_SECONDS_PER_QUESTION = 2;
const CHEAT_DISQUALIFY_COUNT = 3;

module.exports = {
  QUIZ_DURATION_SECONDS,
  MIN_SECONDS_PER_QUESTION,
  CHEAT_DISQUALIFY_COUNT,
};
